# Generated by Django 3.2.15 on 2023-09-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_comment_section_share_blg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_section',
            old_name='user_id',
            new_name='Name',
        ),
    ]
